service: app

provider:
  name: aws
  region: us-east-1

plugins:
  - ./vendor/bref/bref

functions:
  web:
    handler: public/index.php
    timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: "*"

    api:
      handler: index.php
      description: ""
      runtime: php-81-fpm
      timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
      events:
        - httpApi: "*"

# Exclude files from deployment
package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
